#+TITLE: 《深入浅出Networking》
#+AUTHOR: wyj
#+EMAIL: rs@whu.edu.cn
#+KEYWORDS: emacs, notes
#+OPTIONS: H:2 toc:t ^:{}
#+STYLE: <link rel="stylesheet" type="text/css" href="./style/style.css" />
* chp4
** p145
   十六进制与二进制之间有着天然的联系，它大大简化了从二进制到ASCII码的转换过程。十六进制好比一座桥梁，将晦涩难懂的二进制世界与我们的世界连接起来
** p153
#+BEGIN_VERSE
大多数协议规定了消息长度的上限。也就是说原始的消息必须分割成多组消息，打包发送。
消息被打包成两种格式：数据帧(frame)和数据包(packet)
#+END_VERSE
** p154
#+BEGIN_VERSE
数据帧的逻辑结构方便所有的网络设备读取其中的信息。
数据帧内部包含着数据包，数据包才是真正的有效信息。
#+END_VERSE
** p162
#+BEGIN_VERSE
数据包种类很多。每种数据包都包含了若干信息单位。
这些信息单位称为字段(field)，字段包含了与数据包通信相关的信息。
有些字段是各种数据包通用的。
#+END_VERSE
*** UDP数据包
#+BEGIN_VERSE
UDP用于传输流数据，比如音乐和视频
#+END_VERSE
*** ICMP数据包
#+BEGIN_VERSE
ICMP用来测试网络连接状态，使用Ping命令时会用到它
#+END_VERSE
*** TCP数据包
#+BEGIN_VERSE
TCP用于在IP网络上进行可靠的数据通信。
这里“可靠”的含义是指信息不会丢失
#+END_VERSE
** p164
#+BEGIN_VERSE
问题：数据包和数据帧不是一回事吗？
回答：不是的。在以太网上传输的是数据帧。数据帧内的负载数据才是数据包。
通常数据帧必须遵守某一传输协议，比如以太网协议、异步传输模式(ATM)协议、令牌环(Token Ring)协议等
问题：数据包和数据报(datagram)是一回事吗？
回答：它们不完全是一回事。
数据包泛指所有用数据包传输的数据。
数据报也是一种数据包，它特指用不可靠协议(比如UDP协议、ICMP协议)传输的数据包
#+END_VERSE
** p168
#+BEGIN_VERSE
消息有时被分装在许多数据帧里，这是为什么呢？
1. 单个以太网数据帧最多只能装下1500字节的数据。如果发送数据大于1500字节，就必须分多次传输。
2. 为了实现可靠的数据传输，发送方和接收方会使用TCP协议来沟通传输情况。一旦接收方收到出错的数据包，发送方会重新发送。
   如果所有的数据都装在一个数据包里，在网络不稳定的情况下，数据也许永远没法成功发送出去。
#+END_VERSE
** p169
#+BEGIN_VERSE
由于网络中有许多路由器，每个数据包可能选择不同的路径到达目的地。如果数据包选择了距离较远或带宽较低的路径，就会较迟到达目的地。
也就是说，数据包到达终点的顺序可能与出发的顺序不同
#+END_VERSE
** p170
#+BEGIN_VERSE
每个数据包都携带了一个编号，就是存放在序列号字段中的数字。
只要将数据包的编号从小到大排列，就能还原正确地顺序
#+END_VERSE
* chp5
** p181
#+BEGIN_VERSE
*网络不仅仅是由计算机组成的*
公司的网络不仅仅由计算机和服务器组成，还包括集线器(hub)、交换机(switch)、路由器(router)等网络设备。
集线器、交换机用于连接局域网或内部网，路由器用于连接广域网或互联网
#+END_VERSE
** p184
#+BEGIN_VERSE
集线器只是一台中继设备。无论接收到什么信号，它都原封不动地转发给所有端口。
#+END_VERSE
** p186
#+BEGIN_VERSE
交换机可以讲信号解读成数据帧，并利用数据帧包含的信息，将其转发到对应的端口。
#+END_VERSE
** p199
#+BEGIN_VERSE
路由器与计算机一样，拥有自己的MAC地址。如果密电是通过路由器发送的，我们就只能追查到路由器。
路由器后面的计算机组成一个IP子网。
路由器的作用是连接不同的IP子网。
交换机只能根据数据帧的目的MAC地址发送数据帧，它不能跨IP子网工作；
而路由器可以解读接收到的数据包，根据数据包的目的IP地址转发数据包，因而它可以跨IP子网工作
#+END_VERSE
** p200
#+BEGIN_VERSE
路由器的端口数比交换机要少，因为它主要负责连接IP子网，而交换机主要负责连接计算机
计算机通常不会直接连接到路由器
#+END_VERSE
* chp6
** p211
#+BEGIN_VERSE
连接两个网络必须使用路由器。路由器担任两个网络的“翻译”；交换机功能太简单，胜任不了这项工作。
路由器“翻译”网络IP地址。两个网络就像两个城市，路由器负责把一个网络的数据顺利传往另一个网络
#+END_VERSE
** p214
#+BEGIN_VERSE
MAC地址是硬件唯一的标示符，但是MAC地址不包含网络位置信息
IP地址可以分成两个部分：网段地址和主机地址。网段地址用来区分不同的网络，主机地址用于在同一网段内区分不同的主机。
IP地址本身带有分组信息，方便组成IP网络。
#+END_VERSE
** p215
#+BEGIN_VERSE
IP地址的网段地址构成地址空间，让不同的网络相互通信，相当于电话号码中区号的作用。
IP地址的主机地址则用来在该网段中唯一标识主机(节点)。
#+END_VERSE
** p216
#+BEGIN_VERSE
*地址解析协议(Address Resolution Protocol, ARP)实现IP地址到MAC地址的转换*
如果TCP/IP网络上的节点希望通过交换机向某一IP地址发送数据，必须先知道该IP地址对应的MAC地址。这就要用到ARP协议
#+END_VERSE
** p218
#+BEGIN_VERSE
问题：我原以为只要知道对方的MAC地址就能向他发送消息
回答：在以太网内部确实是这样，以太网数据帧里含有各种协议的数据包。
     但是TCP/IP网络是可以跨越多个以太网通信的， *跨网通信必须使用IP地址*
问题：我的计算机已经分配到IP地址，还要MAC地址做什么？
回答：计算机使用的网络协议不止一种。它用IP地址与其他网络的计算机通信；用MAC地址与局域网内的计算机通信。
#+END_VERSE
** p222
#+BEGIN_VERSE
*局域网有一个默认的网关，这个网关就是路由器的IP地址。所有发往网外的数据都默认发给网关，即路由器*
交换机根据MAC地址转发数据
路由器根据IP地址转发数据
#+END_VERSE
** p223
#+BEGIN_VERSE
*记住，交换机只能理解MAC地址*
以太网交换机只能读取数据帧的MAC地址，它不能修改数据帧
路由器要把数据包从数据帧里提取出来，读取其中的IP地址。
如果数据时发往另一个网络的，路由器还要修改数据帧的目的MAC地址和源MAC地址，然后再将数据帧转发出去
#+END_VERSE
** p227
#+BEGIN_VERSE
子网掩码用来指定IP地址中网段地址的长度。
路由器借助IP地址和子网掩码来选择路由
#+END_VERSE
** p254
#+BEGIN_VERSE
问题：路由器端口是指什么？
回答：端口是路由器的物理网络接口，可以是RJ-45接口、串行接口、光缆接口
问题：路由器端口名称中的0/0、0/1代表什么？
回答：有些路由器装有多块网卡，每个网卡上又有多个端口。第1个数字代表路由器中的某种网卡，第2个数字代表该网卡上的某个端口。
     例如0/1代表0号网卡上的1号端口。
#+END_VERSE
** p257
#+BEGIN_VERSE
traceroute命令也向目的IP地址发送数据包，它记录沿途经过的路由器IP地址。
traceroute命令返回的结果是从发送发到接收方之间的完整路由信息(途径路由器的IP地址)
#+END_VERSE
** p264
#+BEGIN_VERSE
*利用RIP协议自动更新路由表*
路由信息协议(Routing Information Protocol, RIP)就是一种动态路由协议。
RIP协议可以用来共享网络地址。路由器可以利用它相互交换路由信息，定期更新路由表
#+END_VERSE
* chp8
** p293
#+BEGIN_VERSE
www.hfhealthclub.com中的www是主机名，用来指明域中的服务器
#+END_VERSE
** p294
#+BEGIN_VERSE
不要混淆了域名和网站名。严格来说，hfhealthclub.com是域名，www.hfhealthclub.com是网站名
#+END_VERSE
** p321
#+BEGIN_VERSE
DNS服务器允许把一个域名捆绑到多个IP地址上。
这样像Google这样的大公司就可以让成千上万台服务器共用www.google.com这个域名了
#+END_VERSE
* chp10
** p374
#+BEGIN_VERSE
DHCP是动态主机配置协议(Dynamic Host Configuration Protocol)的英文缩写
它允许网络设备自动连接无线接入点获取IP地址，无须手动设置
#+END_VERSE
** p380
#+BEGIN_VERSE
NAT是网络地址转换(Network Address Translation)的英文缩写。
它可以为无线接入点提供更多的IP地址。
有了NAT，想要多少IP地址都不愁
#+END_VERSE
